window.PORTFOLIO_PROJECTS = [
  {
    id: 'rejse',
    image: './img/rejse.jpg',
    link: 'https://www.figma.com/design/nQoqaiIfauW1XJPrjNk1QR/Rejseguiden---indi?node-id=0-1',
    featured: true,
    nameKey: 'project.rejse.name',
    descKey: 'project.rejse.desc',
    ctaKey: 'project.rejse.cta',
    tags: { da: ['UI/UX', 'Figma', 'Eksamen'], en: ['UI/UX', 'Figma', 'Exam'] },
    period: { da: '2025', en: '2025' },
    role: { da: 'Multimediedesigner', en: 'Multimedia designer' },
  },
  {
    id: 'spotit',
    image: './img/spotit.jpg',
    link: 'https://www.figma.com/design/kUzIUy2ro9ySPaQXYsS6lv/Spotit?node-id=0-1',
    featured: true,
    nameKey: 'project.spotit.name',
    descKey: 'project.spotit.desc',
    ctaKey: 'project.spotit.cta',
    tags: { da: ['App-koncept', 'UX', 'Prototype'], en: ['App concept', 'UX', 'Prototype'] },
    period: { da: '2024', en: '2024' },
    role: { da: 'UX/UI Designer', en: 'UX/UI Designer' },
  },
  {
    id: 'scana',
    image: './img/scana.jpg',
    link: 'https://www.figma.com/design/btokcDvaZFa0bwUqdy6CVo/Scana?node-id=0-1',
    featured: true,
    nameKey: 'project.scana.name',
    descKey: 'project.scana.desc',
    ctaKey: 'project.scana.cta',
    tags: { da: ['UI/UX', 'Figma', 'Sideprojekt'], en: ['UI/UX', 'Figma', 'Side project'] },
    period: { da: '2024', en: '2024' },
    role: { da: 'Product Designer', en: 'Product Designer' },
  },
  {
    id: 'naturnat',
    image: './img/naturnat.jpg',
    link: 'https://www.figma.com/design/ASh38NdwAIztKCogff8dmV/Naturnat?node-id=0-1',
    featured: false,
    nameKey: 'project.naturnat.name',
    descKey: 'project.naturnat.desc',
    ctaKey: 'project.naturnat.cta',
    tags: { da: ['Web', 'API', 'Responsivt'], en: ['Web', 'API', 'Responsive'] },
    period: { da: '2024', en: '2024' },
    role: { da: 'Frontend Developer', en: 'Frontend Developer' },
  },
];
